<?php
/**
 * MessagesHistoryMessageAttachmentType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VK api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.131
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VkApi\Model\Message;
use VkApi\Lib\ObjectSerializer;
use VkApi\Model\ModelInterface;

/**
 * MessagesHistoryMessageAttachmentType Class Doc Comment
 *
 * @category Class
 * @description Attachments type
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesHistoryMessageAttachmentType
{
    /**
     * Possible values of this enum
     */
    public const PHOTO = 'photo';

    public const VIDEO = 'video';

    public const AUDIO = 'audio';

    public const DOC = 'doc';

    public const LINK = 'link';

    public const MARKET = 'market';

    public const WALL = 'wall';

    public const SHARE = 'share';

    public const GRAFFITI = 'graffiti';

    public const AUDIO_MESSAGE = 'audio_message';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PHOTO,
            self::VIDEO,
            self::AUDIO,
            self::DOC,
            self::LINK,
            self::MARKET,
            self::WALL,
            self::SHARE,
            self::GRAFFITI,
            self::AUDIO_MESSAGE
        ];
    }
}


