<?php
/**
 * MessagesChatRestrictions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VK api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.131
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VkApi\Model\Message;

use ArrayAccess;
use InvalidArgumentException;
use JsonSerializable;
use VkApi\Lib\ObjectSerializer;
use VkApi\Model\ModelInterface;

/**
 * MessagesChatRestrictions Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MessagesChatRestrictions implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'messages_chat_restrictions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'admins_promote_users' => 'bool',
        'only_admins_edit_info' => 'bool',
        'only_admins_edit_pin' => 'bool',
        'only_admins_invite' => 'bool',
        'only_admins_kick' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'admins_promote_users' => null,
        'only_admins_edit_info' => null,
        'only_admins_edit_pin' => null,
        'only_admins_invite' => null,
        'only_admins_kick' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'admins_promote_users' => false,
		'only_admins_edit_info' => false,
		'only_admins_edit_pin' => false,
		'only_admins_invite' => false,
		'only_admins_kick' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'admins_promote_users' => 'admins_promote_users',
        'only_admins_edit_info' => 'only_admins_edit_info',
        'only_admins_edit_pin' => 'only_admins_edit_pin',
        'only_admins_invite' => 'only_admins_invite',
        'only_admins_kick' => 'only_admins_kick'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'admins_promote_users' => 'setAdminsPromoteUsers',
        'only_admins_edit_info' => 'setOnlyAdminsEditInfo',
        'only_admins_edit_pin' => 'setOnlyAdminsEditPin',
        'only_admins_invite' => 'setOnlyAdminsInvite',
        'only_admins_kick' => 'setOnlyAdminsKick'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'admins_promote_users' => 'getAdminsPromoteUsers',
        'only_admins_edit_info' => 'getOnlyAdminsEditInfo',
        'only_admins_edit_pin' => 'getOnlyAdminsEditPin',
        'only_admins_invite' => 'getOnlyAdminsInvite',
        'only_admins_kick' => 'getOnlyAdminsKick'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('admins_promote_users', $data ?? [], null);
        $this->setIfExists('only_admins_edit_info', $data ?? [], null);
        $this->setIfExists('only_admins_edit_pin', $data ?? [], null);
        $this->setIfExists('only_admins_invite', $data ?? [], null);
        $this->setIfExists('only_admins_kick', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets admins_promote_users
     *
     * @return bool|null
     */
    public function getAdminsPromoteUsers()
    {
        return $this->container['admins_promote_users'];
    }

    /**
     * Sets admins_promote_users
     *
     * @param bool|null $admins_promote_users Only admins can promote users to admins
     *
     * @return self
     */
    public function setAdminsPromoteUsers($admins_promote_users)
    {

        if (is_null($admins_promote_users)) {
            throw new InvalidArgumentException('non-nullable admins_promote_users cannot be null');
        }

        $this->container['admins_promote_users'] = $admins_promote_users;

        return $this;
    }

    /**
     * Gets only_admins_edit_info
     *
     * @return bool|null
     */
    public function getOnlyAdminsEditInfo()
    {
        return $this->container['only_admins_edit_info'];
    }

    /**
     * Sets only_admins_edit_info
     *
     * @param bool|null $only_admins_edit_info Only admins can change chat info
     *
     * @return self
     */
    public function setOnlyAdminsEditInfo($only_admins_edit_info)
    {

        if (is_null($only_admins_edit_info)) {
            throw new InvalidArgumentException('non-nullable only_admins_edit_info cannot be null');
        }

        $this->container['only_admins_edit_info'] = $only_admins_edit_info;

        return $this;
    }

    /**
     * Gets only_admins_edit_pin
     *
     * @return bool|null
     */
    public function getOnlyAdminsEditPin()
    {
        return $this->container['only_admins_edit_pin'];
    }

    /**
     * Sets only_admins_edit_pin
     *
     * @param bool|null $only_admins_edit_pin Only admins can edit pinned message
     *
     * @return self
     */
    public function setOnlyAdminsEditPin($only_admins_edit_pin)
    {

        if (is_null($only_admins_edit_pin)) {
            throw new InvalidArgumentException('non-nullable only_admins_edit_pin cannot be null');
        }

        $this->container['only_admins_edit_pin'] = $only_admins_edit_pin;

        return $this;
    }

    /**
     * Gets only_admins_invite
     *
     * @return bool|null
     */
    public function getOnlyAdminsInvite()
    {
        return $this->container['only_admins_invite'];
    }

    /**
     * Sets only_admins_invite
     *
     * @param bool|null $only_admins_invite Only admins can invite users to this chat
     *
     * @return self
     */
    public function setOnlyAdminsInvite($only_admins_invite)
    {

        if (is_null($only_admins_invite)) {
            throw new InvalidArgumentException('non-nullable only_admins_invite cannot be null');
        }

        $this->container['only_admins_invite'] = $only_admins_invite;

        return $this;
    }

    /**
     * Gets only_admins_kick
     *
     * @return bool|null
     */
    public function getOnlyAdminsKick()
    {
        return $this->container['only_admins_kick'];
    }

    /**
     * Sets only_admins_kick
     *
     * @param bool|null $only_admins_kick Only admins can kick users from this chat
     *
     * @return self
     */
    public function setOnlyAdminsKick($only_admins_kick)
    {

        if (is_null($only_admins_kick)) {
            throw new InvalidArgumentException('non-nullable only_admins_kick cannot be null');
        }

        $this->container['only_admins_kick'] = $only_admins_kick;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


