<?php
/**
 * MessagesMessageActionStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VK api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.131
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VkApi\Model\Message;
use VkApi\Lib\ObjectSerializer;
use VkApi\Model\ModelInterface;

/**
 * MessagesMessageActionStatus Class Doc Comment
 *
 * @category Class
 * @description Action status
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesMessageActionStatus
{
    /**
     * Possible values of this enum
     */
    public const PHOTO_UPDATE = 'chat_photo_update';

    public const PHOTO_REMOVE = 'chat_photo_remove';

    public const CREATE = 'chat_create';

    public const TITLE_UPDATE = 'chat_title_update';

    public const INVITE_USER = 'chat_invite_user';

    public const KICK_USER = 'chat_kick_user';

    public const PIN_MESSAGE = 'chat_pin_message';

    public const UNPIN_MESSAGE = 'chat_unpin_message';

    public const INVITE_USER_BY_LINK = 'chat_invite_user_by_link';

    public const INVITE_USER_BY_MESSAGE_REQUEST = 'chat_invite_user_by_message_request';

    public const SCREENSHOT = 'chat_screenshot';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PHOTO_UPDATE,
            self::PHOTO_REMOVE,
            self::CREATE,
            self::TITLE_UPDATE,
            self::INVITE_USER,
            self::KICK_USER,
            self::PIN_MESSAGE,
            self::UNPIN_MESSAGE,
            self::INVITE_USER_BY_LINK,
            self::INVITE_USER_BY_MESSAGE_REQUEST,
            self::SCREENSHOT
        ];
    }
}


