<?php
/**
 * MessagesMessageAttachmentType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VK api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.131
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VkApi\Model\Message;
use VkApi\Lib\ObjectSerializer;
use VkApi\Model\ModelInterface;

/**
 * MessagesMessageAttachmentType Class Doc Comment
 *
 * @category Class
 * @description Attachment type
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesMessageAttachmentType
{
    /**
     * Possible values of this enum
     */
    public const PHOTO = 'photo';

    public const AUDIO = 'audio';

    public const VIDEO = 'video';

    public const DOC = 'doc';

    public const LINK = 'link';

    public const MARKET = 'market';

    public const MARKET_ALBUM = 'market_album';

    public const GIFT = 'gift';

    public const STICKER = 'sticker';

    public const WALL = 'wall';

    public const WALL_REPLY = 'wall_reply';

    public const ARTICLE = 'article';

    public const POLL = 'poll';

    public const CALL = 'call';

    public const GRAFFITI = 'graffiti';

    public const AUDIO_MESSAGE = 'audio_message';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PHOTO,
            self::AUDIO,
            self::VIDEO,
            self::DOC,
            self::LINK,
            self::MARKET,
            self::MARKET_ALBUM,
            self::GIFT,
            self::STICKER,
            self::WALL,
            self::WALL_REPLY,
            self::ARTICLE,
            self::POLL,
            self::CALL,
            self::GRAFFITI,
            self::AUDIO_MESSAGE
        ];
    }
}


