<?php
/**
 * MessagesHistoryMessageAttachment
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VK api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.131
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VkApi\Model\Message;

use ArrayAccess;
use InvalidArgumentException;
use JsonSerializable;
use VkApi\Lib\ObjectSerializer;
use VkApi\Model\ModelInterface;

/**
 * MessagesHistoryMessageAttachment Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MessagesHistoryMessageAttachment implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'messages_history_message_attachment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'audio' => '\OpenAPI\Client\Model\AudioAudio',
        'audio_message' => 'MessagesAudioMessage',
        'doc' => '\OpenAPI\Client\Model\DocsDoc',
        'graffiti' => 'MessagesGraffiti',
        'link' => '\OpenAPI\Client\Model\BaseLink',
        'market' => 'MarketMarketItem',
        'photo' => '\OpenAPI\Client\Model\PhotosPhoto',
        'type' => 'MessagesHistoryMessageAttachmentType',
        'video' => '\OpenAPI\Client\Model\VideoVideo',
        'wall' => '\OpenAPI\Client\Model\WallWallpostFull'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'audio' => null,
        'audio_message' => null,
        'doc' => null,
        'graffiti' => null,
        'link' => null,
        'market' => null,
        'photo' => null,
        'type' => null,
        'video' => null,
        'wall' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'audio' => false,
		'audio_message' => false,
		'doc' => false,
		'graffiti' => false,
		'link' => false,
		'market' => false,
		'photo' => false,
		'type' => false,
		'video' => false,
		'wall' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'audio' => 'audio',
        'audio_message' => 'audio_message',
        'doc' => 'doc',
        'graffiti' => 'graffiti',
        'link' => 'link',
        'market' => 'market',
        'photo' => 'photo',
        'type' => 'type',
        'video' => 'video',
        'wall' => 'wall'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'audio' => 'setAudio',
        'audio_message' => 'setAudioMessage',
        'doc' => 'setDoc',
        'graffiti' => 'setGraffiti',
        'link' => 'setLink',
        'market' => 'setMarket',
        'photo' => 'setPhoto',
        'type' => 'setType',
        'video' => 'setVideo',
        'wall' => 'setWall'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'audio' => 'getAudio',
        'audio_message' => 'getAudioMessage',
        'doc' => 'getDoc',
        'graffiti' => 'getGraffiti',
        'link' => 'getLink',
        'market' => 'getMarket',
        'photo' => 'getPhoto',
        'type' => 'getType',
        'video' => 'getVideo',
        'wall' => 'getWall'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('audio', $data ?? [], null);
        $this->setIfExists('audio_message', $data ?? [], null);
        $this->setIfExists('doc', $data ?? [], null);
        $this->setIfExists('graffiti', $data ?? [], null);
        $this->setIfExists('link', $data ?? [], null);
        $this->setIfExists('market', $data ?? [], null);
        $this->setIfExists('photo', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('video', $data ?? [], null);
        $this->setIfExists('wall', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets audio
     *
     * @return OpenAPI\Client\Model\AudioAudio|null
     */
    public function getAudio()
    {
        return $this->container['audio'];
    }

    /**
     * Sets audio
     *
     * @param OpenAPI\Client\Model\AudioAudio|null $audio audio
     *
     * @return self
     */
    public function setAudio($audio)
    {

        if (is_null($audio)) {
            throw new InvalidArgumentException('non-nullable audio cannot be null');
        }

        $this->container['audio'] = $audio;

        return $this;
    }

    /**
     * Gets audio_message
     *
     * @return MessagesAudioMessage|null
     */
    public function getAudioMessage()
    {
        return $this->container['audio_message'];
    }

    /**
     * Sets audio_message
     *
     * @param MessagesAudioMessage|null $audio_message audio_message
     *
     * @return self
     */
    public function setAudioMessage($audio_message)
    {

        if (is_null($audio_message)) {
            throw new InvalidArgumentException('non-nullable audio_message cannot be null');
        }

        $this->container['audio_message'] = $audio_message;

        return $this;
    }

    /**
     * Gets doc
     *
     * @return OpenAPI\Client\Model\DocsDoc|null
     */
    public function getDoc()
    {
        return $this->container['doc'];
    }

    /**
     * Sets doc
     *
     * @param OpenAPI\Client\Model\DocsDoc|null $doc doc
     *
     * @return self
     */
    public function setDoc($doc)
    {

        if (is_null($doc)) {
            throw new InvalidArgumentException('non-nullable doc cannot be null');
        }

        $this->container['doc'] = $doc;

        return $this;
    }

    /**
     * Gets graffiti
     *
     * @return MessagesGraffiti|null
     */
    public function getGraffiti()
    {
        return $this->container['graffiti'];
    }

    /**
     * Sets graffiti
     *
     * @param MessagesGraffiti|null $graffiti graffiti
     *
     * @return self
     */
    public function setGraffiti($graffiti)
    {

        if (is_null($graffiti)) {
            throw new InvalidArgumentException('non-nullable graffiti cannot be null');
        }

        $this->container['graffiti'] = $graffiti;

        return $this;
    }

    /**
     * Gets link
     *
     * @return OpenAPI\Client\Model\BaseLink|null
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param OpenAPI\Client\Model\BaseLink|null $link link
     *
     * @return self
     */
    public function setLink($link)
    {

        if (is_null($link)) {
            throw new InvalidArgumentException('non-nullable link cannot be null');
        }

        $this->container['link'] = $link;

        return $this;
    }

    /**
     * Gets market
     *
     * @return MarketMarketItem|null
     */
    public function getMarket()
    {
        return $this->container['market'];
    }

    /**
     * Sets market
     *
     * @param MarketMarketItem|null $market market
     *
     * @return self
     */
    public function setMarket($market)
    {

        if (is_null($market)) {
            throw new InvalidArgumentException('non-nullable market cannot be null');
        }

        $this->container['market'] = $market;

        return $this;
    }

    /**
     * Gets photo
     *
     * @return OpenAPI\Client\Model\PhotosPhoto|null
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     *
     * @param OpenAPI\Client\Model\PhotosPhoto|null $photo photo
     *
     * @return self
     */
    public function setPhoto($photo)
    {

        if (is_null($photo)) {
            throw new InvalidArgumentException('non-nullable photo cannot be null');
        }

        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets type
     *
     * @return MessagesHistoryMessageAttachmentType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param MessagesHistoryMessageAttachmentType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {

        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets video
     *
     * @return OpenAPI\Client\Model\VideoVideo|null
     */
    public function getVideo()
    {
        return $this->container['video'];
    }

    /**
     * Sets video
     *
     * @param OpenAPI\Client\Model\VideoVideo|null $video video
     *
     * @return self
     */
    public function setVideo($video)
    {

        if (is_null($video)) {
            throw new InvalidArgumentException('non-nullable video cannot be null');
        }

        $this->container['video'] = $video;

        return $this;
    }

    /**
     * Gets wall
     *
     * @return OpenAPI\Client\Model\WallWallpostFull|null
     */
    public function getWall()
    {
        return $this->container['wall'];
    }

    /**
     * Sets wall
     *
     * @param OpenAPI\Client\Model\WallWallpostFull|null $wall wall
     *
     * @return self
     */
    public function setWall($wall)
    {

        if (is_null($wall)) {
            throw new InvalidArgumentException('non-nullable wall cannot be null');
        }

        $this->container['wall'] = $wall;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


